# Generated by Django 5.2.7 on 2025-10-03 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Material')),
                ('tipo', models.CharField(choices=[('melamina', 'Melamina'), ('mdf', 'MDF'), ('osb', 'OSB'), ('terciado', 'Terciado'), ('aglomerado', 'Aglomerado'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Material')),
                ('espesor', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Espesor (mm)')),
                ('ancho', models.IntegerField(verbose_name='Ancho (mm)')),
                ('largo', models.IntegerField(verbose_name='Largo (mm)')),
                ('precio_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por m²')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tapacanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tapacanto')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('ancho', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Ancho (mm)')),
                ('espesor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Espesor (mm)')),
                ('precio_metro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Metro')),
                ('stock_metros', models.IntegerField(default=0, verbose_name='Stock en Metros')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tapacanto',
                'verbose_name_plural': 'Tapacantos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Proyecto')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En Proceso'), ('optimizado', 'Optimizado'), ('aprobado', 'Aprobado'), ('produccion', 'En Producción'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('total_materiales', models.IntegerField(default=0, verbose_name='Total de Materiales')),
                ('total_tableros', models.IntegerField(default=0, verbose_name='Total de Tableros')),
                ('total_piezas', models.IntegerField(default=0, verbose_name='Total de Piezas')),
                ('eficiencia_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Eficiencia Promedio (%)')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total')),
                ('archivo_pdf', models.CharField(blank=True, max_length=200, null=True, verbose_name='Archivo PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MaterialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_tableros', models.IntegerField(verbose_name='Cantidad de Tableros')),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Eficiencia (%)')),
                ('area_utilizada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área Utilizada (cm²)')),
                ('costo_material', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Material')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_utilizados', to='core.proyecto')),
                ('tapacanto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tapacanto')),
            ],
            options={
                'verbose_name': 'Material del Proyecto',
                'verbose_name_plural': 'Materiales del Proyecto',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfilOptimizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('cliente', 'Cliente'), ('visualizador', 'Solo Visualización')], default='operador', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
