# Generated by Django 5.2.7 on 2025-10-06 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='configuracion',
            field=models.JSONField(blank=True, null=True, verbose_name='Configuración del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='resultado_optimizacion',
            field=models.JSONField(blank=True, null=True, verbose_name='Resultado de Optimización'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_optimizador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
