# Generated by Django 5.2.7 on 2025-10-13 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizacion_remove_cliente_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Conversación')),
                ('es_grupal', models.BooleanField(default=False, verbose_name='Es Grupo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('participantes', models.ManyToManyField(related_name='conversaciones', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('enviado_en', models.DateTimeField(auto_now_add=True, verbose_name='Enviado en')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado')),
                ('editado_en', models.DateTimeField(blank=True, null=True, verbose_name='Editado en')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='chat/archivos/', verbose_name='Archivo Adjunto')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversacion', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['enviado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeLeido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido_en', models.DateTimeField(auto_now_add=True, verbose_name='Leído en')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensaje', verbose_name='Mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje Leído',
                'verbose_name_plural': 'Mensajes Leídos',
                'unique_together': {('usuario', 'mensaje')},
            },
        ),
    ]
