# Generated by Django 5.2.7 on 2025-10-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversacion_mensaje_mensajeleido'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='tapacanto',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tapacanto',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('codigo', 'organizacion')},
        ),
        migrations.AlterUniqueTogether(
            name='tapacanto',
            unique_together={('codigo', 'organizacion')},
        ),
    ]
