# Generated by Django 5.2.7 on 2025-10-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_proyecto_unique_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='public_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID del Proyecto'),
        ),
    ]
