# Generated by Django 5.2.7 on 2025-10-20 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_multi_org_and_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='material',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='run_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ejecutado en'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='usuarioperfiloptimizador',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('org_admin', 'Administrador de Organización'), ('agente', 'Agente'), ('subordinador', 'Subordinador')], default='agente', max_length=20, verbose_name='Rol'),
        ),
    ]
