# Generated by Django 5.2.7 on 2025-10-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_conversacion_organizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfiloptimizador',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar contraseña'),
        ),
    ]
