# Generated by Django 5.2.7 on 2025-10-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_operador_to_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="rut",
            field=models.CharField(max_length=12, verbose_name="RUT"),
        ),
        migrations.AlterField(
            model_name="usuarioperfiloptimizador",
            name="rol",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrador"),
                    ("org_admin", "Administrador de Organización"),
                    ("agente", "Agente"),
                    ("subordinador", "Subordinador"),
                    ("operador", "Operador"),
                ],
                default="agente",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={("rut", "organizacion")},
        ),
    ]
